<%@ page language="java" contentType="text/html; charset=utf-8"%>
<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean"%>
<%@ taglib uri="/WEB-INF/c.tld" prefix="c"%>
<%@ taglib uri="/WEB-INF/fmt.tld" prefix="fmt"%>
<tr id="a${X_OBJECT.id}" align="center">
<td width="27px">${X_OBJECT.carkind }</td>
<td width="32px">${X_OBJECT.asn }</td>
<td width="36px"><fmt:formatNumber value="${X_OBJECT.m1}" pattern="#"/></td>
<td width="29px"><fmt:formatNumber value="${X_OBJECT.mouth}" pattern="#"/></td>
<td width="26px"><fmt:formatNumber value="${X_OBJECT.d1}" pattern="#"/></td>
<td width="29px"><fmt:formatNumber value="${X_OBJECT.pbs}" pattern="#"/></td>
<td width="29px"><fmt:formatNumber value="${X_OBJECT.prj}" pattern="#"/></td>
<td width="32px"><fmt:formatNumber value="${X_OBJECT.wbs}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.sum1}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day1}" pattern="#"/></td>
<!-- 046 -->
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day2}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day3}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day4}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day5}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day6}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day7}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day8}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day9}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day10}" pattern="#"/></td>
<!-- 22-23 -->
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day11}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day12}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day13}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day14}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day15}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day16}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day17}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day18}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day19}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day20}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day21}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day22}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day23}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day24}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day25}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day26}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day27}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day28}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day29}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day30}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day31}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day32}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day33}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day34}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day35}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day36}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day37}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day38}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day39}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day40}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day41}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day42}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day43}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day44}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day45}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day46}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day47}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day48}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day49}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day50}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day51}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day52}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day53}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day54}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day55}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day56}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day57}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day58}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day59}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day60}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day61}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day62}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day63}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day64}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.hourplan_day65}" pattern="#"/></td>
<td width="30px"><fmt:formatNumber value="${X_OBJECT.rem}" pattern="#"/></td>
<td width="50px"><fmt:formatNumber value="${X_OBJECT.sum}" pattern="#"/></td>
<td width="30px"><fmt:formatNumber value="${X_OBJECT.weitou}" pattern="#"/></td>
<td width="32px"><fmt:formatNumber value="${X_OBJECT.lco}" pattern="#"/></td>
<td width="32px"><fmt:formatNumber value="${X_OBJECT.lcx}" pattern="#"/></td>
<td width="26px"><fmt:formatNumber value="${X_OBJECT.hourAll}" pattern="#"/></td>

<tr>